### PR TITLE
fix: if autoHide changes from true to false, make sure to clear the timer

### PR DESCRIPTION
**Pull request by jstheoriginal**
I had an issue where showing a toast via a setTimeout with the following conditions would unexpectedly autohide the toast:
- default toast instance is set to autoHide: true
- then present a Modal containing a Toast with one of the default toast instances
- use a setTimeout to delay showing a toast, with autoHide: false
- the toast presented in the modal would still autohide (unexpected).

This code change makes it behave correctly and clear any autohide timer if the value changes.

I tried to write a failing test for the existing code, but couldn't get it to ever fail my expectations. If you have ideas on how to write a test for this one, I'd welcome the help.

Here's a video showing the issue with existing code:

https://user-images.githubusercontent.com/5117473/145053526-b2b4dd64-d691-4e90-8166-1e90f39cad45.mp4

Here's a video showing the resolved issue with the code in this PR:

https://user-images.githubusercontent.com/5117473/145053561-ca1488c0-00ab-42d5-91df-1fa2994ae753.mp4

### CODE REVIEW

**Comment by calintamas** [comment]
I'll try to write a failing test and let you know what I come up with. 

I'm thinking of: show toast (autohide: true), advance time by half the visibility time, manually hide toast, show another toast (autohide: false), advance time by half the visibility time, expect last toast to be hidden automatically (even though it should not)

**Comment by jstheoriginal** [comment]
> I'll try to write a failing test and let you know what I come up with.
> 
> I'm thinking of: show toast (autohide: true), advance time by half the visibility time, manually hide toast, show another toast (autohide: false), advance time by half the visibility time, expect last toast to be hidden automatically (even though it should not)

I tried many combinations of that including advancing time partway, but i didn't try adding hiding into the mix.

I just pushed another commit as I found out the real reason this happens.

I logged out what happens to get a clue:

```
=== show called.
=== in useEffect Object {
  "autoHide": true,
  "isVisible": true,
}
=== starting timer.
=== in useEffect Object {
  "autoHide": false,
  "isVisible": true,
}
=== Auto hiding.
=== in useEffect Object {
  "autoHide": false,
  "isVisible": false,
}
```

this clued me in that it was isVisible changing that triggered the useEffect before the options got set, which triggers another useEffect.

so by moving the `setVisible(true)` to be after the options are set, it solves the issue. 

Do you think it still makes sense to have the clearTimer logic in place? I think so. I could see a case where a toast is shown, then a second is shown while the first is still visible, and the first had autoHide set to true, but the second has it set to false. With the change I made, it would still successfully cancel hiding the modal since the second one shouldn't autohide.

**Comment by calintamas** [comment]
Yes, I agree `clearTimer` should be there.

With regards to the tests, I managed to write a failing one. And the good news is that it passes with your fix. Thank you! Hopefully my assumptions are right there: last test case from commit https://github.com/calintamas/react-native-toast-message/pull/294/commits/b9ffc591a6bed5f960d8f356bc11e8e64fd4bcc0.

Please take a look, if everything seems fine to you as well I'll merge it (and publish everything in v2.1.0 🎉)

**Comment by jstheoriginal** [comment]
Looks good to me! Thanks for figuring out the tests! 😌

**Comment by calintamas** [comment]
Awesome! Then I'll prepare the release.

And I want to thank you again for all your work (and thorough debugging!) on these 2 issues. I feel like this is the way open source should look like, it's been really nice working with you 🙌

**Pull request merged**
