### PR TITLE
Improved accessibility of text style props for customized toast messages

### LINKED ISSUE #478: Inconsistent Availability of text1 and text2 Style Props in toast.show Function
Currently, in the React Native Toast Message library, the text1 and text2 style props are available in the BaseToastProps, but they are not accessible through the toast.show function. This inconsistency limits the flexibility of customizing the text styles when displaying toast messages.

The text1 and text2 style props are crucial for allowing developers to modify the appearance of toast messages on a case-by-case basis. However, the inability to utilize these props via the toast.show function hampers the ability to dynamically change the text styles when using the library.

It would be beneficial to enhance the library's functionality by ensuring that the text1 and text2 style props are accessible through the toast.show function. This modification would empower developers to easily modify the text styles when displaying toast messages, resulting in a more versatile and customizable user experience.

By addressing this issue, React Native Toast Message can provide a more comprehensive solution for developers, enabling them to create visually consistent and appealing toast messages across their applications.

### PR DESCRIPTION
**Pull request by EmreKarslan**
Made modifications to enhance the accessibility of text style props in React Native Toast Message library. The existing implementation caused issues when customizing toast messages in my application, particularly with regard to the text style. To address this, I adjusted the code to ensure that the text-style props are easily accessible and can be modified according to specific requirements. These changes resolve the issues I encountered and provide a smoother experience when customizing toast messages.

closes #478

### CODE REVIEW

**Comment by calintamas** [comment]
Hi @EmreKarslan, Thanks for your contribution! However, I suggest adding `text1Style` and `text2Style` to `ToastOptions` type, instead of `ToastData` - for sake of correctness, from a conceptual point of view.

**Comment by calintamas** [comment]
@EmreKarslan when you can, please check the failing test `FAIL src/__tests__/useToast.test.ts`

**Comment by EmreKarslan** [comment]
Hey @calintamas, it seems the problem stems from mergeIfDefined. I was passing null as the default value. I think I fixed it when I added text1 and text2 styles as defaults.

**Comment by calintamas** [comment]
@EmreKarslan the expected value needs to be updated in the test case. I suggest keeping the defaults to `null` (there is no point in duplicating styles) and updating the test case.

**Comment by calintamas** [comment]
thank you, released in [2.1.9](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.1.9)

**Pull request merged**
