### PR TITLE
Bugfix/number of line props

### PR DESCRIPTION
**Pull request by mortocks**
Pull request for [textXNumberOfLines](https://github.com/calintamas/react-native-toast-message/pull/152) was not passing the props text1NumberOfLines and text2NumberOfLines down to the child components. I've added this and written some tests

### CODE REVIEW

**Comment by calintamas** [comment]
Hi @mortocks, thanks for the contribution! 

However, the reason why these props are not passed down is because the way to change the Toast layout for a particular `type` is to use `BaseToast` and pass props to alter its layout there:

```js
import Toast, { BaseToast } from 'react-native-toast-message'

const toastConfig = {
  success: ({ text1, props, ...rest }) => (
    <BaseToast
      {...rest}
      style={{ borderLeftColor: 'pink' }}
      contentContainerStyle={{ paddingHorizontal: 15 }}
      text1Style={{
        fontSize: 15,
        fontWeight: '400'
      }}
      text1={text1}
      text2={props.uuid}
      text1NumberOfLines={2}
      text2NumberOfLines={4}
    />
  ),
};

function App(props) {
  // pass `toastConfig` to the Toast instance
  return (
    <>
      <Toast config={toastConfig} ref={(ref) => Toast.setRef(ref)} />
    </>
  );
}

export default App;
```

This is done in order not to clutter the Toast instance with too many props, but rather have a way to extend the layouts / types as much as needed - through the config.

**Comment by mortocks** [comment]
Thanks @calintamas . Interesting, I didn't realise that was the method to use. I'm assuming with this method though you have to override every toast type rather than setting more of a "default prop" e.g

```js
const toastConfig = {
  success: ({ text1, props, ...rest }) => (
    <BaseToast
      {...rest}
      text1NumberOfLines={2}
      text2NumberOfLines={4}
    />
  ),
  error: ({ text1, props, ...rest }) => (
    <BaseToast
      {...rest}
      text1NumberOfLines={2}
      text2NumberOfLines={4}
    />
  ),
  other: ({ text1, props, ...rest }) => (
    <BaseToast
      {...rest}
      text1NumberOfLines={12}
      text2NumberOfLines={140}
    />
  ),
  // even more...
};

function App(props) {
  // pass `toastConfig` to the Toast instance
  return (
    <>
      <Toast config={toastConfig} ref={(ref) => Toast.setRef(ref)} />
    </>
  );
}

export default App;
```

Is that correct?

**Comment by calintamas** [comment]
@mortocks yes, that's correct. You override the Toast types you want with the layouts you want. In my opinion, I think this makes it more flexible / expressive, even if it's a little verbose

**Comment by mortocks** [comment]
Fair enough. Thanks for the explanation

**Pull request closed without merging**
