### PR TITLE
fix: Toast pop up randomly when other popup/dialog opens

### LINKED ISSUE #428: Toast pop up randomly when other popup/dialog opens
**Describe the bug**
I have declared Toast component in the Root Container. Because of this while any other dialog or popup like Android Permission dialog appears on screen, an Empty toast also shows on top of screen.

**Expected behavior**
Toast should not be displayed until Toast.show is called

**Environment (please complete the following information):**
 - OS: Android
 - react-native-toast-message version: ^2.1.5
 - react-native version 0.67.2

### PR DESCRIPTION
**Pull request by rchavik**
closes #428

### CODE REVIEW

**Comment by calintamas** [comment]
Hey, thanks for taking the time! Unfortunately, by doing this, the hiding animation would break.

**Comment by rchavik** [comment]
Uh.. I have moved the `isVisible` check to `renderComponent`. Would this work?

**Comment by calintamas** [comment]
I think it still doesn't solve it. Can you maybe try it out?

**Comment by rchavik** [comment]
sorry, missed it about issues with hiding animation.   i don't know then, at the moment i don't really care about hiding animation

closing for now.

**Pull request closed without merging**
