### PR TITLE
use StyleProp for ts

### PR DESCRIPTION
**Pull request by hamishhossack**
To allow different types of style to be used `(eg. style={[styles.one, styles.two]})`

### CODE REVIEW

**Review by calintamas — APPROVED** [review]
Thank you!

**Comment by jzxchiang1** [comment]
@calintamas Can you release this soon in a new version? Thanks!

**Comment by calintamas** [comment]
> @calintamas Can you release this soon in a new version? Thanks!

@jzxchiang1 Hi, I'll port it to v2 and let you know once it's published

**Comment by calintamas** [comment]
@jzxchiang1 Published in v2.1.0

**Comment by jzxchiang1** [comment]
> @jzxchiang1 Published in v2.1.0

Thank you!

**Pull request merged**
